ASPMaster/Controllers/HomeController.cs
using ASPMaster.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPMaster.Controllers
{
    public class HomeController : Controller
    {
        private DataBase db = new DataBase();
        // GET: /Home/
        public ActionResult Index()
        {
            var produits = db.Produits.ToList();
            return View(produits);
        }

        public ActionResult listerCategorie()
        {
            var Catg = db.Categories.ToList();
            return View(Catg); ;
        }

        public ActionResult listerProduitCategorie(string categorie)
        {
            var produitListe = db.Categories.Include("Produits")
                .Single(g => g.Nom == categorie);

            return View(produitListe);
        }


        public ActionResult listerType()
        {
            var type = db.Types.ToList();
            return View(type); ;
        }

        public ActionResult listerProduitType(string type)
        {
            var produitListe = db.Types.Include("Produits")
                .Single(g => g.Nom == type);

            return View(produitListe);
        }
    }
}

ASPMaster/Controllers/PanierController.cs
using ASPMaster.Helpes;
using ASPMaster.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Data.Entity;


namespace ASPMaster.Controllers
{
    [Authorize]
    public class PanierController : Controller
    {
        DataBase db = new DataBase();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;


        public PanierController()
        {
        }
       
        // GET: Produits/lister
        public ActionResult Lister()
        {
            var produits = db.Produits.ToList();
            return View(produits);
        }
        public PanierController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }


        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.Liste = ListeCart.Instance.Items;
            ViewBag.total = ListeCart.Instance.GetSubTotal();

            var iduser = db.Paniers.Include(a => a.ApplicationUser);
            return View(iduser);

        }

        [AllowAnonymous]
        public ActionResult AjouterProduit(int? id )
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Produit pp = db.Produits.Find(id);


            ListeCart.Instance.AddItem(pp);
            ViewBag.Liste = ListeCart.Instance.Items;
            ViewBag.total = ListeCart.Instance.GetSubTotal();
            return View();

        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult PlusProduit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Produit pp = db.Produits.Find(id);
            ListeCart.Instance.AddItem(pp);
            Item trouve = null;

            foreach (Item a in ListeCart.Instance.Items)
            {
                if (a.Prod.ProduitId == pp.ProduitId)
                    trouve = a;
            }

            var results = new {
                                ct = 1  ,
                                Total = ListeCart.Instance.GetSubTotal () ,
                                Quatite = trouve.quantite ,
                                TotalRow = trouve.TotalPrice 
                                };
            return Json(results) ;
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult MoinsProduit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Produit pp = db.Produits.Find(id);
            ListeCart.Instance.SetLessOneItem(pp);
            Item trouve = null;

            foreach (Item a in ListeCart.Instance.Items)
            {
                if (a.Prod.ProduitId == pp.ProduitId)
                    trouve = a;
            }



            if (trouve != null)
            {
                var results = new
                {
                    
                    Total = ListeCart.Instance.GetSubTotal(),
                    Quatite = trouve.quantite,
                    TotalRow = trouve.TotalPrice,
                    ct = 1 
                };

                return Json(results);

            }
            else
            {
                var results = new
                {
                        ct = 0 
                };

                return Json(results);
            }
            return null;
            

        }

        public ActionResult CheckOut()
        {

            return View();
        }

        [HttpPost]
        public ActionResult CheckOut(FormCollection collection)
        {
            
            
            
            Panier p = new Panier();
 
            p.ApplicationUser = db.Users.Find( User.Identity.GetUserId() ) ;

            db.Paniers.Add(p);
            db.SaveChanges();

            Commande c = new Commande();
            c.Panier = p;
            p.ApplicationUser = db.Users.Find(User.Identity.GetUserId());
            db.Commandes.Add(c);
            db.SaveChanges();


            foreach (Item a in ListeCart.Instance.Items)
            {
                db.ListeCards.Add(new ListeCard(p, a.Prod, a.quantite, a.TotalPrice));
                db.SaveChanges();
            
            }
       
            



            ListeCart.Instance.Items.Clear();

                ViewBag.Message = "Commande effectuée zvec succès";

            return View();

        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult SupprimerProduit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Produit pp = db.Produits.Find(id);
            ListeCart.Instance.RemoveItem(pp);
            var results = new
            {
                Total = ListeCart.Instance.GetSubTotal(),
            };

            return Json(results);
        }
    }
}

ASPMaster/Views/Home/Index.cshtml
@model IEnumerable<ASPMaster.Models.Produit>
@{
    ViewBag.Title = "Index";
    <br />
}

<div class="row">
    <div class="col-lg-4">
        <img class="img-responsive" src="~/Content/tmp/homme1.jpg" alt="Generic placeholder image" style="width: 350px; height: 250px;">
        <h2>Vêtements hommes </h2>
        <p>Les hommes n'ont pas besoin d'une grande garde-robe pour paraître au top...
        <p><a class="btn btn-default" href="/Home/listerProduitType?type=Homme" role="button">Détails »</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <img class="img-responsive" src="~/Content/tmp/femme.png" alt="Generic placeholder image" style="width: 350px; height: 250px;">
        <h2>Vêtements femmes </h2>
        <p>Qui a dit que la mode est éphémère ? Car il n’y a rien d’éphémère...
        <p><a class="btn btn-default" href="/Home/listerProduitType?type=Femme" role="button">Détails »</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <img class="img-responsive" src="~/Content/tmp/enfants.jpg" alt="Generic placeholder image" style="width: 350px; height: 250px;">
        <h2>Vêtements enfants </h2>
        <p>Les parents et la mode enfants ont une chose en commun...
        <p><a class="btn btn-default" href="/Home/listerProduitType?type=Bebe" role="button">Détails »</a></p>
    </div><!-- /.col-lg-4 -->


</div>
<!-- /.row --><br />
@foreach (var produit in Model)
{
    <div class=" col-md-2 col-lg-3">
        <div class="thumbnail">
            <img src="@produit.Image" alt="Computer Man" style="width:250px;height:250px">
            <div class="caption">
                <center>
                    <a href="/Produit/DetailsForUser/@produit.ProduitId" class="btn btn-primary" role="button">Details »</a>
                    <h5>Prix : @produit.Prix</h5>
                    @Html.ActionLink("Ajouter au panier »", "AjouterProduit", "Panier", new { id = @produit.ProduitId }, "")
                </center>
            </div>
        </div>
    </div>
}
<footer>
    <div id="bot">
        <iframe src="https://links.collect.chat/5c03dfde5c854b285067c669" width="300" height="100" frameBorder="0"></iframe>
    </div>
    <p>&copy; @DateTime.Now.Year -.NET project Semester 1 FIA3 G01</p>
</footer>
<style>
    #bot {
        margin-bottom: 20px;
    }

    footer {
        margin-top: -50px;
        height: 300px;
        margin-left: 820px;
        position: fixed;
        background-color: #ff6666;
        margin-bottom: 20px;
        padding-bottom: 50px;
    }

    iframe {
        width: 500px;
        height: 400px;
        padding-bottom: 50px;
    }
</style>

ASPMaster/Views/Home/listerCategorie.cshtml
@model IEnumerable<ASPMaster.Models.Categorie>

@{
    ViewBag.Title = "Index";
    <br /><br /><br /><br /><br /><br />
}
@foreach (var categorie in Model)
{
    <div class=" col-md-3 col-sm-4">
        <div class="thumbnail">
            <div class="caption">
                <center>
                    <a href="/Home/listerProduitCategorie?categorie=@categorie.Nom" class="btn btn-primary" role="button">@categorie.Nom</a>
                </center>
            </div>
        </div>
    </div>
}

ASPMaster/Views/Home/listerProduitCategorie.cshtml
@model ASPMaster.Models.Categorie
@{
    ViewBag.Title = "Produit";
}
<h1>Liste des produits de la catégorie : @Model.Nom</h1>
<br /><br />
@foreach (var produit in Model.Produits)
{
    <div class=" col-md-2 col-lg-3">
        <div class="thumbnail">
            <img src="@produit.Image" alt="Computer Man" style="width:250px;height:200px">
            <div class="caption">
                <center>
                    <a href="/Produit/DetailsForUser/@produit.ProduitId" class="btn btn-primary" role="button">Details »</a>
                    <h5>Prix : @produit.Prix</h5>
                    @Html.ActionLink("Ajouter au panier »", "AjouterProduit", "Panier", new { id = @produit.ProduitId }, "")
                </center>
            </div>
        </div>
    </div>
}

ASPMaster/Views/Home/listerProduitType.cshtml
@model ASPMaster.Models.Type
@{
    ViewBag.Title = "Produit";
}
<h1>Articles pour : @Model.Nom</h1>
<br /><br />
@foreach (var produit in Model.Produits)
{
    <div class=" col-md-2 col-lg-3">
        <div class="thumbnail">
            <img src="@produit.Image" alt="Computer Man" style="width:250px;height:200px">
            <div class="caption">
                <center>
                    <a href="/Produit/DetailsForUser/@produit.ProduitId" class="btn btn-primary" role="button">Details »</a>
                    <h5>Prix : @produit.Prix</h5>
                    @Html.ActionLink("Ajouter au panier »", "AjouterProduit", "Panier", new { id = @produit.ProduitId }, "")
                </center>
            </div>
        </div>
    </div>
}

ASPMaster/Views/Home/listerType.cshtml
@model IEnumerable<ASPMaster.Models.Type>

@{
    ViewBag.Title = "Index";
    <br /><br /><br /><br /><br /><br />
}
@foreach (var type in Model)
{
    <div class=" col-md-3 col-sm-4">
        <div class="thumbnail">
            <div class="caption">
                <center>
                    <a href="/Home/listerProduitType?type=@type.Nom" class="btn btn-primary" role="button">@type.Nom</a>
                </center>
            </div>
        </div>
    </div>
}